---
- name: ios show commands 
  hosts: ios_group
  gather_facts: false
  tasks:
  - name: SYS | Define provider
    set_fact:
      creds:
        host: "{{ device_ip }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
  - name: ios command sh version
    ios_command:
      commands: show version
      host:     "{{device_ip}}"
      username: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
    register: output

  
  - name: debug var output
    debug:
      var: output

  - name: ios command sh int 
    ios_command:
      commands: show interface 
      provider: "{{creds}}"
    register: output

  - name: debug msg output['stdout_lines']
    debug:
      msg: "{{ output['stdout_lines'] }}"

